use_frameworks!
platform :ios, '11.0'

target 'JitsiClientSDK_Example' do
  pod 'JitsiClientSDK', :path => '../'
  pod 'JitsiMeetSDK', '~> 2.8.1'

  target 'JitsiClientSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
